#! /bin/bash
#
# Copyright (c) 2002-2003 SuSE Linux AG Nuernberg, Germany.
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA
#
# Author: Daniele Orlandi <daniele@orlandi.com>
#
# Skel authors: Michal Svec <msvec@suse.cz>
#          Christian Zoz <zoz@suse.de>
# 

usage () {
	echo $@
	echo "Usage: if{up,down}-visdn <config> [<interface>] [-o <options>]"
	echo "  In most cases config==interface, for details see ifup(8)."
	echo
	echo "Options are: option    : explanation"
	echo "All other or wrong options are silently ignored."
	echo
	exit $R_USAGE
}

######################################################################
# change the working direcory and source some common files
#
R_INTERNAL=1      # internal error, e.g. no config or missing scripts
cd /etc/sysconfig/network || exit $R_INTERNAL
test -f scripts/functions && . scripts/functions || exit $R_INTERNAL
test -f ./config && . ./config

######################################################################
# check arguments and how we are called (in case of links)
#
SCRIPTNAME=${0##*/}
debug $*
ACTION=${SCRIPTNAME#if}
ACTION=${ACTION%%-visdn}  # <--- adapt it to the scriptname !!!!!!!!!!!
case "${ACTION}" in
	up|status|down|check) ;;
	*) usage
esac
INTERFACE=$1
case "$INTERFACE" in ""|-h|*help*) usage; esac
shift
if [ -n "$1" -a "$1" != "-o" ] ; then
	CONFIG=$INTERFACE
	INTERFACE=$1
fi
shift
test "$1" = "-o" && shift
OPTIONS="$@"
MODE=manual
while [ $# -gt 0 ]; do
	case $1 in
		boot|onboot) MODE=auto ;;
		hotplug)     MODE=auto ;;
		auto)        MODE=auto ;;
		quiet)       BE_QUIET=yes ;;
		debug)       BE_QUIET=no
		             DEBUG=yes ;;
		*)           debug unknown option $1 ;;
	esac
	shift
done

######################################################################
# check presence of configuration file and source it
#
if [ -f ifcfg-$CONFIG ] ; then
	. ifcfg-$CONFIG
else
	message "could not find configuration file ifcfg-$CONFIG"
fi

######################################################################
# now do what has to be done
#
case $ACTION in
	up)
		if [ $ROLE = "NT" ] ; then
			ifconfig $INTERFACE allmulti
		fi

		message_n "`printf "    %-9s " "$INTERFACE"`"
		message_n "  Role: $ROLE"
		message_n ", Mode: $D_CHANNEL_MODE"

		if [ $STATIC_TEI ] ; then
			message_n ", Static TEI: $STATIC_TEI"
		fi

		message " "

		ip link set $INTERFACE up
		;;
	down)
		ip link set $INTERFACE down
		;;
	status)
		ip link show $INTERFACE
		;;
	check)
		;;
esac
