#! /bin/sh

set -x
libtoolize --copy --force						&& \
(aclocal-1.9 -I config || aclocal -I config)				&& \
autoheader								&& \
(automake-1.9 --add-missing --copy || automake --add-missing --copy)	&& \
autoconf
