#! /bin/bash

set -x

pushd /root/isdn--devel > /dev/null

modprobe ppp_generic
insmod visdn-core/visdn-core.ko
insmod lapd/lapd.ko
insmod visdn-netdev/visdn-netdev.ko
insmod visdn-streamport/visdn-streamport.ko
#insmod visdn-ppp/visdn-ppp.ko
insmod visdn-timer-system/visdn-timer-system.ko
insmod hfc-4s/hfc-4s.ko debug_level=3
insmod hfc-pci/hfc-pci.ko debug_level=3

popd > /dev/null

set +x

function create_netdev()
{
	exec 6<>/dev/visdn/netdev-control
	echo "create lapd" >&6
	NETDEV_CHAN=`cat <&6`
	exec 6<&-
}

function connect_channels()
{
	local CHAN1=$1
	local CHAN2=$2

	echo "$CHAN1,$CHAN2" > /sys/bus/visdn/connect
}

function config_if()
{
	local DEVICE_ID=$1
	local PORT_ID=$2
	local NETDEV_NAME=$3
	local ROLE=$4

        pushd "/sys/devices/$DEVICE_ID" > /dev/null || ( echo "Invalid device ID"; return )

	pushd $PORT_ID > /dev/null || ( echo "Missing port"; return )

	[ -f role ] || ( echo "Missing role"; return )
	[ -f enabled ] || ( echo "Missing enabled"; return )
	[ -f /sys/bus/visdn/connect ] || ( echo "Missing connect"; return )
	[ -c /dev/visdn/netdev-control ] || ( echo "Missing netdev-control"; return )

	echo $ROLE > role

	local D_SYSFS_DIR=`readlink D`
	local D_CHAN=`basename $D_SYSFS_DIR`
	local E_SYSFS_DIR=`readlink E`
	local E_CHAN=`basename $E_SYSFS_DIR`

	if [ ! -L "$D_SYSFS_DIR/connected" ] ; then
		create_netdev

		connect_channels "${NETDEV_CHAN}" "$D_CHAN"
		connect_channels "${NETDEV_CHAN}e" "$E_CHAN"

		nameif -r $NETDEV_NAME visdn${NETDEV_CHAN##*.}d
	fi

	echo 1 > enabled

	if [ $ROLE = "NT" ] ; then
		ip link set $NETDEV_NAME allmulticast on
	else
		ip link set $NETDEV_NAME allmulticast off
	fi

	ip link set $NETDEV_NAME up
popd > /dev/null

popd > /dev/null
}

#create_netdev
#
#echo $NETDEV_CHAN
#
#exit

config_if "pci0000:00/0000:00:07.0" "st0" "visdn0" "TE"
config_if "pci0000:00/0000:00:09.0" "st0" "visdn1.0" "NT"
config_if "pci0000:00/0000:00:09.0" "st1" "visdn1.1" "NT"
config_if "pci0000:00/0000:00:09.0" "st2" "visdn1.2" "TE"
config_if "pci0000:00/0000:00:09.0" "st3" "visdn1.3" "TE"

