#! /bin/bash -x

modprobe ppp_generic
insmod /root/isdn--devel/lapd/lapd.ko
insmod /root/isdn--devel/visdn-core/visdn-core.ko
insmod /root/isdn--devel/visdn-netdev/visdn-netdev.ko
insmod /root/isdn--devel/visdn-streamport/visdn-streamport.ko
insmod /root/isdn--devel/visdn-timer-system/visdn-timer-system.ko
insmod /root/isdn--devel/hfc-4s/hfc-4s.ko debug_level=3
insmod /root/isdn--devel/hfc-pci/hfc-pci.ko debug_level=3


config_if() {

	local DEVICE_ID=$1
	local PORT_ID=$2
	local NETDEV_NAME=$3
	local ROLE=$4

        pushd "/sys/devices/$DEVICE_ID" || ( echo "Invalid device ID"; return )

	pushd $PORT_ID || ( echo "Missing port"; return )

	[ -f role ] || ( echo "Missing role"; return )
	[ -f enabled ] || ( echo "Missing enabled"; return )
	[ -f /sys/bus/visdn/connect ] || ( echo "Missing connect"; return )
	[ -c /dev/visdn/netdev-control ] || ( echo "Missing netdev-control"; return )

	echo $ROLE > role

	local D_SYSFS_DIR=`readlink D`
	local D_CHAN=`basename $D_SYSFS_DIR`

	if [ ! -L "$D_SYSFS_DIR/connected" ] ; then
		local NETDEV_CHAN=`cat /dev/visdn/netdev-control`
		echo "${NETDEV_CHAN},${D_CHAN}" > /sys/bus/visdn/connect

		nameif -r $NETDEV_NAME visdn${NETDEV_CHAN##*.}d
	fi

	echo 1 > enabled

	if [ $ROLE = "NT" ] ; then
		ip link set $NETDEV_NAME allmulticast on
	else
		ip link set $NETDEV_NAME allmulticast off
	fi

	ip link set $NETDEV_NAME up
popd

popd
}

config_if "pci0000:00/0000:00:09.0" "st0" "visdn1.0" "NT"
config_if "pci0000:00/0000:00:09.0" "st1" "visdn1.1" "NT"
config_if "pci0000:00/0000:00:09.0" "st2" "visdn1.2" "TE"
config_if "pci0000:00/0000:00:09.0" "st3" "visdn1.3" "TE"
config_if "pci0000:00/0000:00:07.0" "st0" "visdn0" "TE"

