#! /bin/bash
#
# vGSM udev helper script
#
# Copyright (C) 2007 Daniele Orlandi
#
# Authors: Daniele "Vihai" Orlandi <daniele@orlandi.com>
#
# This program is free software and may be modified and distributed
# under the terms and conditions of the GNU General Public License.
#

SYS_ROOT="/sys"
BUS_TYPE=$PHYSDEVBUS
BUS_LOCATION=$(basename "$PHYSDEVPATH")
CONF_DIR="/etc/vgsm/devices"

SERIAL_NUMBER_FILE="$SYS_ROOT/$PHYSDEVPATH/serial_number"

if [ -f "$SERIAL_NUMBER_FILE" ]; then
	SERIAL=$(<$SERIAL_NUMBER_FILE)
fi

CONF_FILE_LOC="$CONF_DIR/$BUS_TYPE-$BUS_LOCATION"
CONF_FILE_SER="$CONF_DIR/serial-$SERIAL"

if [ -f "$CONF_FILE_LOC" ]; then
	CONF_FILE=$CONF_FILE_LOC
elif [ -f "$CONF_FILE_SER" ]; then
	CONF_FILE=$CONF_FILE_SER
else
	exit 0
fi

while read LINE; do

	COMMAND=$(echo "$LINE" | awk '{ print $1 }')
	PAR=$(echo "$LINE" | awk '{ print $2 }')

	if [ $COMMAND == 'name' ]; then
		DEVICE_NAME=$PAR
	fi
done < $CONF_FILE

if [ "$DEVICE_NAME" ]; then
	PREFIX="${DEVICE_NAME}_"
else
	PREFIX=""
fi

echo -n "vgsm/$PREFIX"
echo -n $1 | sed 's/^vgsm_\(mea\|mesim\|me\|sim\).*/\1/'
echo $(expr $MINOR % 8)
