#! /bin/sh

function usage()
{
	echo "Usage: $0 protocol devname"
}

if [ ! "$1" -o ! "$2" ]; then
	usage
	exit
fi

NETDEV_PROTOCOL=$1
NETDEV_REQ_DEVNAME=$2

exec 6<>/dev/visdn/netdev-control
echo "create $NETDEV_PROTOCOL $NETDEV_REQ_DEVNAME" >&6
read -u 6 NETDEV_DEVNAME
read -u 6 NETDEV_CHAN_D
read -u 6 NETDEV_CHAN_E
exec 6<&-

echo "devname: $NETDEV_DEVNAME"
echo "d_channel: $NETDEV_CHAN_D"
echo "e_channel: $NETDEV_CHAN_E"
