#ifndef Q931_LOG_H
#define Q931_LOG_H

#define LOG_DEBUG	Q931_LOG_DEBUG
#define LOG_INFO	Q931_LOG_INFO
#define LOG_NOTICE	Q931_LOG_NOTICE
#define LOG_WARNING	Q931_LOG_WARNING
#define LOG_ERR		Q931_LOG_ERR
#define LOG_CRIT	Q931_LOG_CRIT
#define LOG_ALERT	Q931_LOG_ALERT
#define LOG_EMERG	Q931_LOG_EMERG

#endif
